[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
scholarship = "SCHOLARSHIP_PROGRAM_ID_REPLACE_ME"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
